# Generated by Django 4.1.3 on 2022-11-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
    ]
